### ISSUE TITLE
princurve 2.0.2 has been released

### ISSUE THREAD

**Issue by rcannood** [dgrun/FateID#1]
Hello Dominic @dgrun!

I just updated princurve to version 2.0.2 [on CRAN](https://cran.r-project.org/web/packages/princurve/index.html). I noticed the `FateID` package uses `princurve` and wanted to notify you of the changes made so you can update your package accordingly.

The `principal.curve` function has been renamed to `principal_curve`, in order to get `princurve` up-to-date with current R naming conventions. In order to make the names of the parameters more self explanatory, the argument `plot.true` has been renamed to `plot_iterations`, and the output variable `tag` has been renamed to `ord`.

The function `principal.curve` still exists in the package, for now, as not to break your package. On July 1st, however, this function will become deprecated, and will later on be removed.

If you have any remarks or questions, feel free to let me know!
Robrecht

**Comment by dgrun** [comment]
Dear Robrecht,

thanks for the notification. When will the binaries be updated?

Best wishes,
Dominic


On Tue, Jun 12, 2018 at 7:03 PM, Robrecht Cannoodt <notifications@github.com

**Comment by rcannood** [comment]
They take a while to build. By now, all of them except the old R releases OSX have been built :)

**Comment by dgrun** [comment]
Thanks. I just installed R 3.5 and your package works for me now - but this
R version has other problems it seems...

On Mon, Jun 18, 2018 at 8:56 PM, Robrecht Cannoodt <notifications@github.com

**Comment by dgrun** [comment]
I still cannot update the FateID package. With the binaries of R 3.5 it
works, but for R 3.4.4 I get an error when I try to install from source

*/var/folders/qr/60yvs97j7j1d3fgzhl43hh900000gq/T//ccE3WUVH.s:1011:11:
note: change section name to "__text"*

        .section __TEXT,__textcoal_nt,coalesced,pure_instructions

*                 ^      ~~~~~~~~~~~~~*

make: *** [getlam.o] Error 1

ERROR: compilation failed for package ‘princurve’

* removing
‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/princurve’

* restoring previous
‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/princurve’

If I want to ensure backward compatibility this needs to be solved before I
can update the FateID package.

Thanks,
Dominic

On Mon, Jun 18, 2018 at 8:56 PM, Robrecht Cannoodt <notifications@github.com

**Comment by dgrun** [comment]
I'm working on a MacBook with macOS High Sierra Version 10.13.4.

**Comment by rcannood** [comment]
Hi Dominic,

That's a strange error. I enabled travis to build princurve for R versions 3.4 (oldrel) and 3.5 (release), for both osx and linux. Unfortunately, the oldrel on osx [builds without errors](https://travis-ci.org/dynverse/princurve/jobs/399095362). 

```r
$ Rscript -e 'sessionInfo()'
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3
```

How are you trying to install princurve? Just `install.packages("princurve")`? What version of Xcode are you using?

Robrecht

**Comment by dgrun** [comment]
I'm installing it by install.packages("princurve") after starting R from
the terminal. My Xcode version is 9.4.1 (9F2000).

**Comment by rcannood** [comment]
Apparently it's something to do with your version of GCC ([link1](https://stackoverflow.com/questions/39865367/warning-section-textcoal-nt-is-deprecate-since-updating-to-mac-osx-sierra), [link2](https://github.com/Homebrew/homebrew-core/issues/4812), [many more examples](https://www.google.com/search?q=macos+note%3A+change+section+name+to+%22__text%22)).

Since I didn't change anything to the Fortran code, I assume you also get the error with one of the older versions of princurve?

**Comment by dgrun** [comment]
Can you make binaries available for previous R versions (R3.4 and higher)?
I would like to update FateID, but people using an older version of R
should be able to install it on a similar architecture like mine.

**Comment by rcannood** [comment]
The binary release should be [available on CRAN](https://cran.r-project.org/web/packages/princurve/index.html) already. You can find it [here](https://cran.r-project.org/bin/macosx/el-capitan/contrib/3.4/princurve_2.0.2.tgz).

Could you try something for me? Could you confirm whether you get the same error when you install the github version using `devtools::install_github("dynverse/princurve")`? If so, could you also try out whether you get the same error using `devtools::install_github("dynverse/princurve@feature/remove_fortran")`?

**Comment by dgrun** [comment]
When I install from R3.4.4 I(from any repo) I don't see a version 2.0.2
binary. This is what I get:

> install.packages("princurve")

--- Please select a CRAN mirror for use in this session ---


  There is a binary version available but the source version is later:

          binary source needs_compilation

princurve 1.1-12  2.0.2              TRUE



Installation only worked with this command : devtools::install_github("
dynverse/princurve@feature/remove_fortran")
(not the other - same error there)

**Comment by rcannood** [comment]
> Installation only worked with this command : devtools::install_github("
dynverse/princurve@feature/remove_fortran")
(not the other - same error there)

That's great! It took quite a bit of effort, but I ported the fortran code to Rcpp. This way, you should not get the compilation warning anymore on your platform.

I just submitted princurve 2.0.3 (which includes this fix) to CRAN; I'll let you know when it is available.

**Comment by rcannood** [comment]
[princurve 2.0.3](https://cran.r-project.org/web/packages/princurve/index.html) is now on CRAN! It will take a while before the binaries are built, though.

Does this version of princurve work on your platform when you install from source?

**Comment by dgrun** [comment]
Yes, I could install, but I still have to test the updated FateID package.

Thanks a lot!

On Wed, Jul 4, 2018 at 11:43 AM, Robrecht Cannoodt <notifications@github.com

**Comment by dgrun** [comment]
Package updated!

**Comment by rcannood** [comment]
:+1: fantastic!
