### ISSUE TITLE
Importing from Seurat

### ISSUE THREAD

**Issue by kasumaz** [dgrun/FateID#2]
Dear Developers, 
I noticed in the paper (Herman, Sagar, and Grün 2018) that Seurat was used also. Have you ever tried to import a seurat object into fateID? If you have, i could work in this way and adjust the script accordingly by giving consensus genes of interest. I would like to know how I can do this (if its not alot of work) and if there was ever a script around to do this. 
Thanks a lot.

**Comment by dgrun** [comment]
Hi,

we have not implemented a direct import of a Seurat object into FateID yet.
In the study we used the count matrix independently for Seurat and FateID.
It should be straight forward to extract a filtered count matrix from
Seurat and use it as input for FateID. We will consider adding an interface
to FateID.

Best regards,
Dominic

**Comment by kasumaz** [comment]
Hi, 
I have ran the tutorial and all works. I am having trouble in how to make a list of elements with my own matrix (in generated in collaboration with Onur Basak) in the same way for the intestines dataset. Would you happen to have that script used for the intestines data or could I send someone a matrix along with cell/cluster IDs needed that might be able to do it quickly for me and send me the script? I usually up and running once I get of the ground. Ive tried for a couple of days to get it going. 
Many thanks, 
Kaz

**Comment by dgrun** [comment]
Could you send the piece of code that gives you an error? Maybe I can
help...
Thanks!
Dominic

**Comment by kasumaz** [comment]
Hi, 
I have problems at the start: 

This first part I dont need I think because I already have clusters identified with the RaceID algorithm (done at Utrecht). But I try it anyhow since the next step below also gives errors. 
If I run this: 
tar <- c(6,7)
FMarker <- list(c("Hopx","Ascl1","Hes5"), "Plp1", "Mbp")
xf <- getFeat(x,tar,FMarker,fpv=.05)

I have this error: 
> xf <- getFeat(x,tar,FMarker,fpv=.05)
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
In addition: Warning messages:
1: In y != i :
  longer object length is not a multiple of shorter objec
![R Environment](https://user-images.githubusercontent.com/31452870/58548161-14652400-8209-11e9-8302-ea124339f645.jpg)
t length
2: In y == i :
  longer object length is not a multiple of shorter object length


If I try this part:

rc <- reclassify(x, y, tar, clthr=.75, nbfactor=5, use.dist=FALSE, seed=12345, nbtree=NULL, q=0.9) 
I have this error: 
> rc <- reclassify(x, y, tar, clthr=.75, nbfactor=5, use.dist=FALSE, seed=12345, nbtree=NULL, q=0.9)
Error in randomForest.default(xr, as.factor(pr), xt, nbtree = nbtree,  : 
  Need at least two classes to do classification.

I have taken a pic of the items in the environment incase I have the wrong format of an object there. 
Any help will be greatly appreciated. In the matrix, I used the unnormalised values since there is a step that does it near the start. 
Any hints would be great. 
Many thanks, 
Kaz 

P.S. apologies for the jpeg. I cant seem to move it around to the bottom.

**Comment by dgrun** [comment]
The arguments for getFeat are incorrect. It does not take 'FMarker' as an
argument. The second argument 'y' is a clustering partition, i.e. a vector
with cluster numbers for all cells; the third argument is 'tar' Type
help(getFeat). For the 'reclassify' function please also check your 'y'
argument.

Best,
Dominic

**Comment by kasumaz** [comment]
Hi, 
I am not able to move beyond this part: 

rc <- reclassify(x, y, tar, z=NULL,clthr=.9, nbfactor=5, use.dist=FALSE, seed=12345, nbtree=NULL, q=0.9)

> rc <- reclassify(x, y, tar, z=NULL,clthr=.9, nbfactor=5, use.dist=FALSE, seed=12345, nbtree=NULL, q=0.9)
Error in randomForest.default(xr, as.factor(pr), xt, nbtree = nbtree,  : 
  Need at least two classes to do classification.

Also, i notice that the ordering of cluster numbers is not the same. It shows up all as 1. 

Would it be possible to send you a matrix with a list of cluster IDs so that perhaps I can follow better what you do whenever you have time and then I do the same for other datasets to come? It would be much easier for me to get this off the ground. 

Many thanks,
Kaz

**Comment by dgrun** [comment]
y has to be a vector with cluster numbers. The names of the vector should
correspond to the column names of x. tar has to be a vector with the
cluster numbers of the target clusters as entry. Did you check if all this
is true?
Best,
Dominic

**Comment by kasumaz** [comment]
Dear Dominic, 
Many thanks. 
I have it mostly working. I had to manually give the cell IDs as a vector as it was not going through if I uploaded as a file. 
There are 2 more things if its okay to ask. 
(1) The v file, I couldnt figure out what this could be as some of the earlier functions require this. Is it something to do with "vf1"  or differential expression as something similar was mentioned in the reference manual? 
(2) Is there a way to change some of the graphic features or parameters of plots? Is there an underlying package like ggplots that I can use to change cell colors over? The legends are always cut out of any plot and I have warnings like: Error in plot.new() : figure margins too large. 
Maybe you have some across this. 
Otherwise, I am nearly there. 
Thanks a lot. 
Kaz

**Comment by dgrun** [comment]
The v file is just a filtered expression matrix, containing only a subset
of genes, e.g. the highly variable ones.

The graphic parameters are hardwired in the plotting functions. Of course,
you could overwrite. I guess this is an R Studio problem. You have to make
the window bigger, and the everything should be displayed.

Best,
Dominic

**Comment by kasumaz** [comment]
Hi,
I hope it is the last time I message you. 

When I run these scripts: 
pr <- plotFateMap(y,dr,k=2,m="tsne",trthr=.33,fb=fb,prc=TRUE) 

pr  <- prcurve(y,fb,dr,k=3,m="tsne",trthr=0.4,start=3)

I have this error: 
Error in svd(xstar) : a dimension is zero 

For this script: 
trc <- dptTraj(x,y,fb,trthr=.25,distance="euclidean",sigma=1000)
I have this error:
Error in if (median((1:length(n))[y[n] == sub("t", "", j)]) < median((1:length(n))[y[n] !=  : 
  missing value where TRUE/FALSE needed

Is there a way I can fix these so there is a trajectory line appearing?  
I thought it might be related to the fb list. 
Thanks a lot.

**Comment by dgrun** [comment]
The first error could have occurred in the principal_curve function which
is imported from the princurve package. I noticed that before in some
cases, but I could not debug this function. However, make sure that your
input is correctly specified. Did you run the examples from the vignette
successfully
The second error is also strange. I could check if you send me a
workspace....

**Comment by kasumaz** [comment]
[R Workspace.zip](https://github.com/dgrun/FateID/files/3261882/R.Workspace.zip)

[Script parly working2.zip](https://github.com/dgrun/FateID/files/3261920/Script.parly.working2.zip)

Hi, 
The vignette works perfect at my end.
I attach the workspace and the script here. 
I am starting with a reduced set of cells with only the most variable genes. 
Maybe once I have the princurve part solved, the other minor issues with heatmaps can be solved too. 
Thanks a lot.

**Comment by dgrun** [comment]
Very simple bug fix:

the vector y with the partition needs component names corresponding to cell
IDs.
Just integrate this line into your script after defining y:

names(y) <- colnames(v)


Then the error messages will disappear.


Your diffexp analysis did not work because there is not target cluster  "t6"


You probably mean:


b <- "t12"


Then this works, too.


I think this solves everything. Good luck!

**Comment by kasumaz** [comment]
Dear Dominic, 
I have it working, at least for the main thing I needed. 

I mention it here incase anyone else wanted to do the same. 
The colours, I wanted to make for clusters to have them match the other figures. The main target cells I would have liked in red since in the confocal pictures (as RFP) and other work in seurat, the target cluster is red. I saved the lists in this way: 

write.csv(dr[["tsne"]][["D2"]], "coordinates.csv")

write.csv(pr[["pr"]][["t13"]][["s"]], "pr_t13.csv")

This allowed me to then just make a plot on ggplots with the trajectory lines and cells in the colours I want them to be. I attach the figure here too. Just to let anyone else know what they can do to customise it a bit more in their own way. 

I wanted to show a plot in the main figure with the important genes. 
Its the last command: 

k <- impGenes(fb,"t13", "t12")
k <- impGenes(fb,"t13")
>Error in hclust(d, method = method) : must have n >= 2 objects to cluster

I tried both ways. I am not able to figure out yet how to overcome this. 

This might be related to last few errors i see in a few of the commands:

trc <- dptTraj(x,y,fb,trthr=.25,distance="euclidean",sigma=1000)
>Error in if (median((1:length(n))[y[n] == sub("t", "", j)]) < median((1:length(n))[y[n] !=  : 
  missing value where TRUE/FALSE needed

g <- names(ps$nodes)[ps$nodes == 1]
> Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete

de <- diffexpnb(v,A=A,B=B,DESeq=FALSE,norm=FALSE,vfit=NULL,locreg=FALSE)
>Error in 0:round(x[1] * length(A) + x[2] * length(B), 0) : 
  NA/NaN argument

#plotting fate bias:
gene2gene(x$v,x$y,"Olig2","Mbp")

I dont think I need to filter any cells with the trc function. But I run it anyways.
 
Its not important to do the differential expression. But it might be related upstream to the impgenes function. There is a part that is needed, the tn in the fb list, i,e, the name of target clusters. Is there a way or format to have this done in the fb file? 

I am nearly there. 
I will get back to it in the end of the week or the week after. There is no rush. I mention all here incase anyone else is troubleshooting too (although I am still new to R). 
 
Many thanks. 
Kaz 



![OLs+NB](https://user-images.githubusercontent.com/31452870/59295556-443e0e00-8c84-11e9-8012-0d17db1068b7.jpg)

**Comment by dgrun** [comment]
Dear Kaz,
could you send me a workspace or code to reproduce the error?
Thx,
Dominic

**Comment by kasumaz** [comment]
[Workspace + Script.zip](https://github.com/dgrun/FateID/files/3301410/Workspace.%2B.Script.zip)
Hi Dominic, 
I attach here the workspace and script as a zip file. 

Errors 1 and 3 below, I cant get around the bugs yet. For Error 2, I use seurat anyhow for acquiring DEGs, but maybe its related to the error 3 (the last thing I need). It would be nice to have a list of important genes that define the trajectories. 
Many thanks, Kaz 


Error 1: 
> trc <- dptTraj(x,y,fb,trthr=.25,distance="euclidean",sigma=1000)
Error in if (median((1:length(n))[y[n] == sub("t", "", j)]) < median((1:length(n))[y[n] !=  : 
  missing value where TRUE/FALSE needed

Error 2: 
> de <- diffexpnb(v,A=A,B=B,DESeq=FALSE,norm=FALSE,vfit=NULL,locreg=FALSE) 
Error in 0:round(x[1] * length(A) + x[2] * length(B), 0) :  NA/NaN argument

Error 3: 
> k <- impGenes(fb,"t13") 
Error in hclust(d, method = method) : must have n >= 2 objects to cluster

**Comment by dgrun** [comment]
Dear Kaz,

regarding Error 3: impGenes has more parameters, there were no genes with
importance > 0.02, so select ithr=0.01

 impGenes(fb,"t12",ithr=0.01,zthr=2)



regarding Error 2: A is empty. There are no cells in clusters 3,4,5 with a
fate bias >thr for "t13". So you could decrease thr for example... with .1
it works; Or add more cluster to 3,4,5


Regarding Error 1: reduce trthr...


Best wishes,

Dominic

**Comment by kasumaz** [comment]
Dear Dominic, 
Everything is now under control and working in my hands. 
Basically absolutely all is working in my hands. 
Many thanks for this. 

In the impgenes plot, the number that run along the column in the heatmap, they refer to the clusters when I look at the Hermann Nature Methods paper in Fig 1C that shows this plot. As I have 8 clusters in total in this analysis, but there are 7 columns running along the heatmap. Is this because the expression values in each time point are compared with the final cell type (the 8th one) in the trajectory so the 8th one isnt shown? Just so I get my facts right when explain in results or figure legends. 

Thanks very much.

**Comment by dgrun** [comment]
The number that runs along the column is the random forest iteration. For
each gene the heatmap indicates the importance at each iteration.
Best,
Dominic

**Comment by kasumaz** [comment]
Okay, everything is clear and smooth now. 
Once again, many thanks.
