### ISSUE TITLE
Running FateID on seurat object issues

### ISSUE THREAD

**Issue by s849** [dgrun/FateID#3]
Hi,

Thank you for developing FateID. I have used the vignette on the original data with no problem. Now, I would like to use FateID in my data set. I have processed my data with Seurat and have a final object on which I want to identify fate biases. I have the following questions;

1. Is there now a function available to import directly from Seurat?
2. If I import my data from Seurat manually, am I right to say that "x" is the un-normalized counts matrix; and "y" will be cell identities? What about "v"? 
3. If I reclassify all remaining cells using the cells within the target clusters as input with FateID, then I do not have to reclassify cells using the full data frame containing all genes can be used as input? (i.e. steps below)
<img width="603" alt="Screen Shot 2020-04-10 at 5 06 46 PM" src="https://user-images.githubusercontent.com/47041278/79030414-ab9b4780-7b4d-11ea-9792-37502669fd96.png">
4. If I reclassify all remaining cells using the cells within the target clusters as input with FateID, do I still need to do feature selection using the _getFeat_ function?
5. I ran into an error while computing the fate bias using _fateBias_ function. The error is the following:

**Error in randomForest.default(xr, as.factor(pr), xt, nbtree = nbtree,   :
     Need at least two classes to do classification.**

After this, I am stuck and cannot proceed. Any help will be much appreciated.

Thanks!

**Comment by dgrun** [comment]
Hi,

there is no function for direct import. All you need is a raw count matrix x and a target cluster partition.

You can retrieve the cluster partition, i.e., y from a Seurat object (sc):

y <- as.numeric(sc@meta.data$seurat_clusters)
names(y) <- rownames(sc@meta.data)

You can then subset the raw count matrix:
x <- x[,names(y)]

v is just a filtered expression matrix. You can filter out lowly expressed genes and/or only keep highly variable genes, e.g. v <- x[sc@assays$RNA@var.features,]

You can reclassify with the filtered v or the full x. I would only use the getFeat function if you work with the full matrix x.

Regarding your error message: For some reason your cluster partition seems to contain only a single class. Perhaps this has happened during the reclassification? Maybe you should skip this reclassification.

I hope it will work now.

**Comment by s849** [comment]
Hi,

Thanks for your response. I am still having problems and ran into two errors. Please see below for my example code;

x <- as.matrix(object@assays$RNA@counts)
head(x[,1:5])

y <- as.numeric(object@meta.data$seurat_clusters)
names(y) <- rownames(object@meta.data)

x <- x[,names(y)]

tar <- c(6)

FMarker <- list(c("Mki67","Top2a"), "Cenpa", "Pttg1")
xf <- getPart(x,FMarker,fthr=NULL,n=5)
head(xf$part)

tar <- xf$tar
y <- xf$part

rc <- reclassify(x, y, tar, clthr=.75, nbfactor=5, use.dist=FALSE, seed=12345, nbtree=NULL, q=0.9)
y  <- rc$part

v <- x[object@assays$RNA@var.features,]
v

x  <- rc$xf
x
x <- getFeat(v,y,tar,fpv=0.01) **##Get error #1**
**Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases**

tar <- c(6)
fb  <- fateBias(x, y, tar, z=NULL, minnr=5, minnrh=10, adapt=TRUE, confidence=0.75, nbfactor=5, use.dist=FALSE, seed=12345, nbtree=NULL) **##Get error #2**
**minnr: 5 
minnrh: 10 
test set size iteration 1 : 5 
randomforest iteration 1 of 5 cells
Error in apply(probs[trt, ], 1, function(x, y) y[which(x == max(x))][1],  : 
  dim(X) must have a positive length**

Any advice will be much appreciated. Thanks!

**Comment by dgrun** [comment]
Hi,

error #1 I cannot explain. Are there NA's in your count table?
Error #2 occurs because your are providing only a single target cluster (6). You need at least two target clusters. Otherwise, the fate bias should anyway be equal to 1 for every cell. If you want me to look into the first error feel free to send me a link to your Seurat object (you can randomise the gene names to not reveal any essential info) by email (gruen@ie-freiburg.mpg.de).

Best,
Dominic

**Comment by s849** [comment]
Hi Dominic,

Thanks for your follow up message. I was able to run FateID using the following commands and without running the reclassifier:

x <- as.matrix(object@assays$RNA@counts)

y <- as.numeric(object@meta.data$seurat_clusters)
names(y) <- rownames(object@meta.data)

x <- x[,names(y)]

tar <- c(6,5)
fb  <- fateBias(x, y, tar, z=NULL, minnr=5, minnrh=10, adapt=TRUE, confidence=0.75, nbfactor=5, use.dist=FALSE, seed=12345, nbtree=NULL)

dr  <- compdr(x, z=NULL, m=c("tsne","cmd","dm","lle","umap"), k=c(2,3), lle.n=30, dm.sigma="local", dm.distance="euclidean", tsne.perplexity=30, seed=12345)

plotFateMap(y,dr,k=2,m="tsne")
plotFateMap(y,dr,k=3,m="tsne")

Does this seem correct?
I was also wondering whether I can project the cell fate bias in the embedding I already have from Seurat instead of creating a new one as it is done with the code I provided above?

Please let me know your thoughts. 

Thanks!

**Comment by dgrun** [comment]
Hi,

the code seems correct to me.

You can simply overwrite entries of dr with Seurat embeddings, e.g., if "object" is your Seurat object

dr$umap$D2 <- as.data.frame(object@reductions$umap@cell.embeddings[rownames(dr$umap$D2),])
